project:
  type: website

website:
  title: "Lipidomics analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: doc/report.Rmd
        text: "Report"
format:
  html:
    theme: simplex

knitr:
  opts_chunk:
    echo: false

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: auto
