---
title: "Draft R Markdown document"
author: "Your Name"
output: html_document
editor_options:
  markdown:
    wrap: 72
    canonical: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Code chunk
```

```{r}
library(dplyr)
load(here::here("data/lipidomics.rda"))
lipidomics %>%
  select(gender, age) %>%
  filter(age >= 25)
```

## This is poorly formatted

-   Definitely should have an empty space above this list.
-   This isn't a list, why not?

## Basic statistics

```{r setup}
library(tidyverse)
library(tidymodels)
lipidomics <- targets::tar_read(lipidomics)
```

```{r}
log_reg_specs <- logistic_reg() |>
  set_engine("glm")
log_reg_specs
```

```{r}



lipidomics_wide <- lipidomics |> 
    column_values_to_snakecase(metabolite) |> 
    metabolites_to_wider()



recipe(lipidomics_wide) %>%
  update_role(metabolite_Lipid_CH_3_1, age, gender, new_role = "predictor") %>%
  update_role(class, new_role = "outcome")
```

```{r}

recipe_specs <- lipidomics_wide %>%
  create_recipe_spec(metabolite_cholesterol)
recipe_specs
```

## Exercises

### Linear regression model definition

```{r}
lm_spect <- parsnip::linear_reg() |> 
    set_engine("lm")
```
